import "./globals.css";
import { Saira_Condensed } from "next/font/google";

const saira = Saira_Condensed({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-saira",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${saira.variable} bg-bgwhite dark:bg-black`}>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
