import { useQuery, gql, useLazyQuery, useMutation } from '@apollo/client';
import Head from 'next/head';
import Image from 'next/image';
import {
  CreateUserMutation,
  CreateUserMutationVariables,
  GetAllUserQuery,
  GetUserQuery,
  GetUserQueryVariables
} from '../graphql/generated/types';
import {
  MUTATION_CREATE_USER,
  QUERY_ALL_DATA,
  QUERY_USER
} from '../graphql/user';

import styles from '../styles/Home.module.css';

export default function Home() {
  const { data, loading, error } = useQuery<GetAllUserQuery>(QUERY_ALL_DATA);
  const [fetchUser, { data: fetchedData }] = useLazyQuery<
    GetUserQuery,
    GetUserQueryVariables
  >(QUERY_USER);
  console.log(fetchedData);

  // mutation
  const [createUser, { data: newData }] = useMutation<
    CreateUserMutation,
    CreateUserMutationVariables
  >(MUTATION_CREATE_USER);

  if (loading) {
    return <h1>loading</h1>;
  }
  if (error) {
    return <h1>error</h1>;
  }
  console.log(data?.users, error);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-8xl text-red-900">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {data?.users.__typename == 'UserSuccessResult' &&
          data?.users?.map(u => {
            return <h1>{u.username}</h1>;
          })}
        <button
          onClick={() => fetchUser({ variables: { userId: '1' } })}
          className="btn-circle btn text-clip text-left font-serif"
        >
          hello
        </button>
        {fetchedData?.user.name}

        <button
          onClick={() =>
            createUser({
              variables: {
                input: {
                  name: 'fahim',
                  username: 'kil',
                  age: 15,
                  nationality: 'bangladeshi'
                }
              }
            })
          }
        >
          mutation
        </button>
        {newData?.createUser.name}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
